version: '3'

volumes:
  data_dev: {}

services:
  django_chime:
    build:
      context: .
      dockerfile: ./compose/django_chime/Dockerfile-dev
    environment:
      - LC_ALL=C.UTF-8
      - LANG=C.UTF-8
      - ENVTYPE=dev
    #env-file:
    #  - ./.envs/.dev/.django_chime
    image: django_chime:dev
    volumes:
      - .:/app
      - data_dev:/data
    #command: /start
