version: '3'

services:
  django_chime:
    build:
      context: .
      dockerfile: ./compose/django_chime/Dockerfile-dev
    environment:
      - LC_ALL=C.UTF-8
      - LANG=C.UTF-8
      - ENVTYPE=dev
    image: django_chime:dev
    volumes:
      - .:/app
