version: '3'

volumes:
  data_test: {}

services:
  django_chime:
    build:
      context: .
      dockerfile: ./compose/django_chime/Dockerfile-test
    environment:
      - LC_ALL=C.UTF-8
      - LANG=C.UTF-8
    image: django_chime:test
    volumes:
      - data_test:/data
